apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: chronicc/demo-backstage
    # backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: hello@chroni.cc
  lifecycle: experimental
